### ISSUE TITLE
qrtools don't decode a router wifi code

### ISSUE THREAD

**Issue by pokulo** [primetang/qrtools#11]
```
Traceback (most recent call last):
  File "/usr/bin/qtqr", line 837, in decodeWebcam
    if qr.data_decode[qr.data_type](qr.data) == 'NULL':
  File "/usr/lib/python3.9/site-packages/qrtools.py", line 110, in <lambda>
    'wifi' : lambda data: re.findall(u"WIFI:S:(.*);T:(.*);P:(.*);[H:]+(.*);", data, re.IGNORECASE)[0],
IndexError: list index out of range
```

This bug keeps qtqr failing when scanning WIFI qr codes generated by FritzBox. Attached a PNG of the failing QR Code. Its content is:

`WIFI:S:WifiName;T:WPA;P:605234075537023465159873240561365314585632096534;;`

```
$ qtqr --version
QtQR version 2.0

$ zbarcam --version
0.23.1
```

Looks to, as if "[H:]+(.*)" may be empty (missing "H:"), but regEx does not match in that case. Changing "[H:]+(.*)" to "[H:]*(.*)" helped in my case, Will create a pull request on GitHub :)

Originally reported here: https://bugs.launchpad.net/qr-tools/+bug/1810167

**Comment by pokulo** [comment]
Does not apply to this unofficial repo.
